# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='image_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
