# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170806_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='image_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
