# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170806_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='department',
            field=models.CharField(choices=[('Art', 'Art'), ('Sport', 'Sport'), ('Science', 'Science'), ('Politics', 'Politics'), ('Trips', 'Trips')], default=('Art', 'Art'), max_length=15),
        ),
    ]
