# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('BirthDate', models.DateTimeField(blank=True, null=True)),
                ('Profile_Photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Studied_at', models.TextField(blank=True, max_length=1000, null=True)),
                ('Adress', models.CharField(blank=True, max_length=200, null=True)),
                ('Mobile_Phone', models.CharField(blank=True, max_length=1000, null=True)),
                ('Current_Workplace', models.CharField(blank=True, max_length=100, null=True)),
                ('Worked_at', models.TextField(blank=True, max_length=1000, null=True)),
                ('Hobbies', models.TextField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
