# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhomepage',
            old_name='user',
            new_name='user_id',
        ),
    ]
