# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170811_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhomepage',
            old_name='BirthDate',
            new_name='Birth_Date',
        ),
    ]
