# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170811_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhomepage',
            name='Profile_Photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
